### ISSUE TITLE
Make hardcoded paths portable

### ISSUE THREAD

**Issue by allemangD** [mturja-vf-ic-bd/SlicerSurfaceLearner#3]
(Quoted from https://github.com/Slicer/ExtensionsIndex/pull/1973)

In several places you use hardcoded paths that will not be correct on other users' machines.

- `PlaneCNN.InferenceLib.CONSTANTS.DEFAULT_FILE_PATHS`
- `PlaneCNNTrainer.DeepLearnerLib.CONSTANTS.DEFAULT_FILE_PATHS`
- `SurfacePlaneMapper.geometry_image.run.HOME`

I suggest computing these paths using `pathlib.Path.home()` instead.

**Comment by mturja-vf-ic-bd** [comment]
@allemangD 
Thanks for noticing that. I have changed the hardcoded paths to a user-specific one here: https://github.com/mturja-vf-ic-bd/SlicerSurfaceLearner/pull/5
